Add buffered for PrintWriter in dumpGfxInfo
The monkey test error:
java.lang.RuntimeException: StrictMode ThreadPolicy violation
...
Caused by: android.os.strictmode.UnbufferedIoViolation

The resolve method:
PrintWrite use BufferedWriter instead of FastPrintWriter.

Tracked-On: OAM-113172
Signed-off-by: Gao, HuadongX <huadongx.gao@intel.com>